name: Build
on: 
  pull_request:
  push: 
    branches:
      - master

jobs:
  build-and-tests:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: 📦 Initialize
        uses: Marfeel/github-actions/providers/widget/initialize@master

      - name: 🛠 Build
        uses: Marfeel/github-actions/providers/widget/build@master

      - name: ✅ Tests
        uses: Marfeel/github-actions/providers/widget/test@master

      - name: 🚀 Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.repository.name != 'widget-providers-template'
        uses: Marfeel/github-actions/providers/widget/publish@master
        with:
            gh-token: ${{ secrets.GH_PACKAGE_REGISTRY_TOKEN }}
            nexus-token: ${{ secrets.NPM_NEXUS_AUTH }}
            build-number: ${{ github.run_id }}
